### ISSUE TITLE
No connect

### ISSUE THREAD

**Issue by GermanCaruncho** [cjaliaga/aioaquarea#49]
Today it stopped working. I have reset, re-uploaded the integration, modified the Panasonic ID and nothing.

An error already mentioned in another thread appears: (https://github.com/cjaliaga/aioaquarea/issues/48#issuecomment-2105353195)

2024-09-11 12:28:08.704 ERROR (MainThread) [custom_components.aquarea.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/aquarea/config_flow.py", line 144, in _validate_input
    await self._api.login()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 274, in login
    await self.__login_production()
  File "/usr/local/lib/python3.12/site-packages/aioaquarea/core.py", line 334, in __login_production
    csrf = response.cookies.get("_csrf").value

**Comment by GermanCaruncho** [comment]
After 256 emails indicating that someone was connecting, I reattached by following the link and now it works.

**Comment by 20220223** [comment]
Same problem here with the same exception. It stopped working today without having anything changed. Could you please explain your fix? 
I assume you followed this link in the "someone was connecting"-email: https://accountglb.digital.panasonic.com/

I logged into the account management service, reset the 2FA and added my phone number. But the problem still exists. Using the Panasonic Comfort Cloud App or the AQUAREA Smart Cloud Website i can still control my device.

**Comment by adamus-tork** [comment]
Not sure if it's the same. Everything was working until I got an email about your comment :D

aioaquarea.errors.AuthenticationError: Authentication error: 1001-0001 - You have been logged out due to inactivity. Please log in again.

It keeps re-logging and panasonic sends an email about the login each time.

**Comment by 20220223** [comment]
You're right. It started like this a few hours ago. Sorry i forgot. After deactivating and reactivating the integration and entering the passwort to manually reconnect, i got

Authentication error: 1001-1401 - Invalid username or password 

and the log shows the unexpected exception mentioned above.
